# Site Settings
title: Felipe Toscano | Diário de Bordo na Web
email: felipe.toscano@gmail.com
description: Blog sobre conhecimentos adquiridos durante estudos em TI.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://felipetoscano.com.br" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Felipe Toscano de Azevedo Cardoso
user_description: Engenheiro de Software, Desenvolvedor Sênior
disqus_username: felipetac

# Social Media
# Remove the item if you don't need it
github_username: felipetac
#facebook_username: facebook_username
#twitter_username: felipe_tac
#instagram_username: instagram_username
linkedin_username: felipetac
#medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
plugins:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Sobre Mim
    url: https://www.linkedin.com/in/felipetac
    external: true
  - title: Contato
    url: /contato/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
